COUNTRIES = [
    'AUSTRIA', 'BIAŁORUŚ', 'BUŁGARIA', 'CHINY',
    'CHORWACJA', 'CZECHY', 'ESTONIA', 'FINLANDIA',
    'FRANCJA', 'HISZPANIA', 'HOLANDIA', 'ISLANDIA',
    'JAPONIA', 'KANADA', 'KAZACHSTAN', 'KOREA POŁUDNIOWA',
    'ŁOTWA', 'NIEMCY', 'NORWEGIA', 'POLSKA', 'ROSJA',
    'RUMINIA', 'SŁOWACJA', 'SŁOWENIA', 'USA',
    'SZWAJCARIA', 'SZWECJA', 'TURCJA', 'UKRAINA',
    'WĘGRY', 'WŁOCHY'
]
